name: nix-build-on-demand-docker
on:
  workflow_dispatch:
    inputs:
      type:
        description: 'Type of the build'
        required: true
        default: 'worker'
      
jobs:
  build-custom-image:
    if: ${{ github.event.inputs.type == 'worker' || github.event.inputs.type == 'control' }}
    name: Build custom image
    runs-on: ubuntu-22.04
    env:
      NIXOS_USER: ${{ secrets.NIXOS_USER }}
      NIXOS_PASSWORD: ${{ secrets.NIXOS_PASSWORD }}
      NIXOS_SSH_PUBKEY: ${{ secrets.NIXOS_SSH_PUBKEY }}
      NIXOS_SSID: ${{ secrets.NIXOS_SSID }}
      NIXOS_SSID_PASSWORD: ${{ secrets.NIXOS_SSID_PASSWORD }}
      NIXOS_HOSTNAME: ${{ secrets.NIXOS_HOSTNAME }}
    steps:
    - uses: actions/checkout@v4.1.1
    - uses: cachix/install-nix-action@v26
      with:
        nix_path: nixos=channel:nixos-23.05
        extra_nix_config: |
          extra-platforms = aarch64-linux
    - name: Check nix.conf
      run: cat /etc/nix/nix.conf
    - name: Register binfmt
      run: |
        docker run --rm --privileged multiarch/qemu-user-static --reset -p yes
    - name: Test binfmt availability
      run: |
        cat /proc/sys/fs/binfmt_misc/qemu-aarch64
    - name: Build SD Image
      run: |
        nix build .#nixosConfigurations.raspberry-pi_3_${{ github.event.inputs.type }}.config.system.build.sdImage
    - uses: actions/upload-artifact@v4
      with:
        name: sd-image.img
        path: ./result/sd-image/*.img*